### ISSUE TITLE
Generating topic for documents

### ISSUE THREAD

**Issue by haskarb** [rsrandhawa/Vec2Topic#1]
Hi!

Thanks for the code. I read your paper and tried your code (web), it is working great. I have query, how should I generate the topic for a document?

Thanks

**Comment by rsrandhawa** [comment]
the web has a default app attempts to identify K=10 topics as a collection of most relevant words associated with each topic in decreasing order of the relevance to that topic. To tweak the K parameter, you need to manually run the code on your end. Hope this helps.

**Comment by dhariyalbhaskar** [comment]
Thanks for replying.

Is there any way to print depth and degree of corresponding words in the file?

**Comment by rsrandhawa** [comment]
You can print out the depth and deg dictionaries in vec2topic() at any point after they have been created (line 283 for depth and 334 for deg)

**Comment by haskarb** [comment]
Yes, thanks. I figured it out.

**Comment by haskarb** [comment]
How do you validate the value of K, if it is correct?

**Comment by rsrandhawa** [comment]
That’s a great question, and unfortunately, there is no formal way of doing this.

**Comment by haskarb** [comment]
Please let me know if I am wrong. Your depth value is calculated based on clustering, while degree is independent of clustering?

**Comment by rsrandhawa** [comment]
Yes that is correct
